# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982ff27073788150cd420835fe8c3babcc060d5c46a9c1eae98cd4c2bdf8f63fb560b6d183a027b47ea6cc5a48ddc2aac4e3b49cf6c26142ceb543d2eecb6765

test:
  secret_key_base: f9fab66df750ae597df5327e9f9227a0b67e39ff2304106100aafc5877caffcca88a328d933495cd1dd3cb871c7294be9fe250e216c06388941f3070d0d27e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
